version: 2

jobs:

  build:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor

  test:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - run:
          name: Run tests!
          command: go test -v $(glide nv)


      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor

  coveralls:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.12.3
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - run:
          name: Coveralls!
          command: goveralls -v -ignore=$(paste -sd, .coverignore) -service=circle-ci -repotoken=$COVERALLS_TOKEN


      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor


# The flow is
#    build
#      |
#      ---------- test
#                   |
#                   ---------- coveralls
#                   |
#                   ---------- docker_build
#
#
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - coveralls:
          requires:
            - test
